### ISSUE TITLE
感觉这份很全，想转载一下，不知可否？

### ISSUE THREAD

**Issue by yuxunyang** [AweiLoveAndroid/CommonDevKnowledge#5]

**Comment by AweiLoveAndroid** [comment]
你可以转载我的简书博客的  这个https://www.jianshu.com/p/c70989bd5f29

**Comment by yuxunyang** [comment]
已部分转载了。http://blog.csdn.net/asahinokawa/article/details/79415701。
虽然基本上只有我自己在看我自己的博客，但是还是表示感谢~

**Comment by AweiLoveAndroid** [comment]
你的博客点不进去。。是不是链接写错了。。

**Comment by zhanzengyu** [comment]
@AweiLoveAndroid 链接把句号算进去了。去掉句号就可以了。哈哈哈

**Comment by yuxunyang** [comment]
哈哈 这句号有点夸张
